{
 "title": "Gateway & Device Monitoring Dashboard",
 "description": "Lux and LED values monitoring per user and device",
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "gateway_user_id",
    "label": "Gateway User",
    "query": "SELECT username AS __text, id AS __value FROM users;"
   },
   {
    "name": "device_id",
    "label": "Select Device(s)",
    "query": "SELECT device_name AS __text, id AS __value FROM devices WHERE user_id = $gateway_user_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "$device_id Use porcentage (%)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "device_id",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "poseidon_db",
     "rawSql": "SELECT \r\n  (100 - value) AS \"Apagado\",\r\n  value AS \"Encendido\"\r\n  \r\nFROM historical \r\nWHERE device_id = ${device_id} \r\nORDER BY recorded_at DESC \r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Average Values (Selected Devices)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT AVG(lux) AS \"average lux\", AVG(value) AS \"average use (%)\" FROM historical h WHERE $__timeFilter(h.recorded_at) AND h.user_id = $gateway_user_id AND h.device_id IN ($device_id);"
    }
   ]
  },
  {
   "title": "Lux over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT h.recorded_at AS \"time\", h.lux AS \"lux\", d.device_name AS metric FROM historical h JOIN devices d ON h.device_id = d.id WHERE $__timeFilter(h.recorded_at) AND h.user_id = $gateway_user_id AND h.device_id IN ($device_id) ORDER BY h.recorded_at;"
    }
   ]
  },
  {
   "title": "LED Value (%) over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT h.recorded_at AS \"time\", h.value AS \"led_value\", d.device_name AS metric FROM historical h JOIN devices d ON h.device_id = d.id WHERE $__timeFilter(h.recorded_at) AND h.user_id = $gateway_user_id AND h.device_id IN ($device_id) ORDER BY h.recorded_at;"
    }
   ]
  },
  {
   "title": "System use mean (%)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "poseidon_db",
     "rawSql": "SELECT\r\n  $__timeGroup(recorded_at, '1m') AS \"time\",\r\n  AVG(value) AS \"Global mean (%)\"\r\nFROM historical\r\nWHERE\r\n  $__timeFilter(recorded_at) AND\r\n  user_id = $gateway_user_id AND\r\n  device_id IN ($device_id)\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  }
 ]
}