apiVersion: 1
datasources:
  - name: PoseidonDB
    type: postgres
    uid: poseidon_prod_db
    url: db:5432
    user: writer
    database: poseidon_db  # <--- ESTA ES LA "DEFAULT DATABASE" QUE TE PIDE
    isDefault: true
    jsonData:
      sslmode: "disable"
      postgresVersion: 15
    secureJsonData:
      password: "1234"
